/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAidatRouteImport } from './routes/_app/aidat'
import { Route as AppAidatAyarlariRouteImport } from './routes/_app/aidat-ayarlari'
import { Route as AppBorclarRouteImport } from './routes/_app/borclar'
import { Route as AppCalisanRaporuRouteImport } from './routes/_app/calisan-raporu'
import { Route as AppDairemRouteImport } from './routes/_app/dairem'
import { Route as AppFirmalarRouteImport } from './routes/_app/firmalar'
import { Route as AppGelirGiderRouteImport } from './routes/_app/gelir-gider'
import { Route as AppGiderlerRouteImport } from './routes/_app/giderler'
import { Route as AppKasaRouteImport } from './routes/_app/kasa'
import { Route as AppKasaAyarlariRouteImport } from './routes/_app/kasa-ayarlari'
import { Route as AppPanelRouteImport } from './routes/_app/panel'
import { Route as AppRaporlarRouteImport } from './routes/_app/raporlar'
import { Route as AppSakinlerRouteImport } from './routes/_app/sakinler'
import { Route as AppSifreRouteImport } from './routes/_app/sifre'
import { Route as AppSitelerRouteImport } from './routes/_app/siteler'
import { Route as AppTahsilatlarRouteImport } from './routes/_app/tahsilatlar'
import { Route as AppTekrarlayanGorevlerRouteImport } from './routes/_app/tekrarlayan-gorevler'
import { Route as AppVardiyalarRouteImport } from './routes/_app/vardiyalar'
import { Route as DavetTokenRouteImport } from './routes/davet.$token'
import { Route as AppCalisanlarIndexRouteImport } from './routes/_app/calisanlar/index'
import { Route as AppCalisanlarEmployeeIdRouteImport } from './routes/_app/calisanlar/$employeeId'
import { Route as AppDairelerIndexRouteImport } from './routes/_app/daireler/index'
import { Route as AppDairelerUnitIdRouteImport } from './routes/_app/daireler/$unitId'
import { Route as AppGorevlerIndexRouteImport } from './routes/_app/gorevler/index'
import { Route as AppGorevlerTaskIdRouteImport } from './routes/_app/gorevler/$taskId'
import { Route as AppIslerIndexRouteImport } from './routes/_app/isler/index'
import { Route as AppIslerWorkIdRouteImport } from './routes/_app/isler/$workId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAidatRoute = AppAidatRouteImport.update({
  id: '/aidat',
  path: '/aidat',
  getParentRoute: () => AppRoute,
} as any)
const AppAidatAyarlariRoute = AppAidatAyarlariRouteImport.update({
  id: '/aidat-ayarlari',
  path: '/aidat-ayarlari',
  getParentRoute: () => AppRoute,
} as any)
const AppBorclarRoute = AppBorclarRouteImport.update({
  id: '/borclar',
  path: '/borclar',
  getParentRoute: () => AppRoute,
} as any)
const AppCalisanRaporuRoute = AppCalisanRaporuRouteImport.update({
  id: '/calisan-raporu',
  path: '/calisan-raporu',
  getParentRoute: () => AppRoute,
} as any)
const AppDairemRoute = AppDairemRouteImport.update({
  id: '/dairem',
  path: '/dairem',
  getParentRoute: () => AppRoute,
} as any)
const AppFirmalarRoute = AppFirmalarRouteImport.update({
  id: '/firmalar',
  path: '/firmalar',
  getParentRoute: () => AppRoute,
} as any)
const AppGelirGiderRoute = AppGelirGiderRouteImport.update({
  id: '/gelir-gider',
  path: '/gelir-gider',
  getParentRoute: () => AppRoute,
} as any)
const AppGiderlerRoute = AppGiderlerRouteImport.update({
  id: '/giderler',
  path: '/giderler',
  getParentRoute: () => AppRoute,
} as any)
const AppKasaRoute = AppKasaRouteImport.update({
  id: '/kasa',
  path: '/kasa',
  getParentRoute: () => AppRoute,
} as any)
const AppKasaAyarlariRoute = AppKasaAyarlariRouteImport.update({
  id: '/kasa-ayarlari',
  path: '/kasa-ayarlari',
  getParentRoute: () => AppRoute,
} as any)
const AppPanelRoute = AppPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AppRoute,
} as any)
const AppRaporlarRoute = AppRaporlarRouteImport.update({
  id: '/raporlar',
  path: '/raporlar',
  getParentRoute: () => AppRoute,
} as any)
const AppSakinlerRoute = AppSakinlerRouteImport.update({
  id: '/sakinler',
  path: '/sakinler',
  getParentRoute: () => AppRoute,
} as any)
const AppSifreRoute = AppSifreRouteImport.update({
  id: '/sifre',
  path: '/sifre',
  getParentRoute: () => AppRoute,
} as any)
const AppSitelerRoute = AppSitelerRouteImport.update({
  id: '/siteler',
  path: '/siteler',
  getParentRoute: () => AppRoute,
} as any)
const AppTahsilatlarRoute = AppTahsilatlarRouteImport.update({
  id: '/tahsilatlar',
  path: '/tahsilatlar',
  getParentRoute: () => AppRoute,
} as any)
const AppTekrarlayanGorevlerRoute = AppTekrarlayanGorevlerRouteImport.update({
  id: '/tekrarlayan-gorevler',
  path: '/tekrarlayan-gorevler',
  getParentRoute: () => AppRoute,
} as any)
const AppVardiyalarRoute = AppVardiyalarRouteImport.update({
  id: '/vardiyalar',
  path: '/vardiyalar',
  getParentRoute: () => AppRoute,
} as any)
const DavetTokenRoute = DavetTokenRouteImport.update({
  id: '/davet/$token',
  path: '/davet/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCalisanlarIndexRoute = AppCalisanlarIndexRouteImport.update({
  id: '/calisanlar/',
  path: '/calisanlar/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalisanlarEmployeeIdRoute = AppCalisanlarEmployeeIdRouteImport.update({
  id: '/calisanlar/$employeeId',
  path: '/calisanlar/$employeeId',
  getParentRoute: () => AppRoute,
} as any)
const AppDairelerIndexRoute = AppDairelerIndexRouteImport.update({
  id: '/daireler/',
  path: '/daireler/',
  getParentRoute: () => AppRoute,
} as any)
const AppDairelerUnitIdRoute = AppDairelerUnitIdRouteImport.update({
  id: '/daireler/$unitId',
  path: '/daireler/$unitId',
  getParentRoute: () => AppRoute,
} as any)
const AppGorevlerIndexRoute = AppGorevlerIndexRouteImport.update({
  id: '/gorevler/',
  path: '/gorevler/',
  getParentRoute: () => AppRoute,
} as any)
const AppGorevlerTaskIdRoute = AppGorevlerTaskIdRouteImport.update({
  id: '/gorevler/$taskId',
  path: '/gorevler/$taskId',
  getParentRoute: () => AppRoute,
} as any)
const AppIslerIndexRoute = AppIslerIndexRouteImport.update({
  id: '/isler/',
  path: '/isler/',
  getParentRoute: () => AppRoute,
} as any)
const AppIslerWorkIdRoute = AppIslerWorkIdRouteImport.update({
  id: '/isler/$workId',
  path: '/isler/$workId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/giris': typeof GirisRoute
  '/aidat': typeof AppAidatRoute
  '/aidat-ayarlari': typeof AppAidatAyarlariRoute
  '/borclar': typeof AppBorclarRoute
  '/calisan-raporu': typeof AppCalisanRaporuRoute
  '/dairem': typeof AppDairemRoute
  '/firmalar': typeof AppFirmalarRoute
  '/gelir-gider': typeof AppGelirGiderRoute
  '/giderler': typeof AppGiderlerRoute
  '/kasa': typeof AppKasaRoute
  '/kasa-ayarlari': typeof AppKasaAyarlariRoute
  '/panel': typeof AppPanelRoute
  '/raporlar': typeof AppRaporlarRoute
  '/sakinler': typeof AppSakinlerRoute
  '/sifre': typeof AppSifreRoute
  '/siteler': typeof AppSitelerRoute
  '/tahsilatlar': typeof AppTahsilatlarRoute
  '/tekrarlayan-gorevler': typeof AppTekrarlayanGorevlerRoute
  '/vardiyalar': typeof AppVardiyalarRoute
  '/davet/$token': typeof DavetTokenRoute
  '/calisanlar/$employeeId': typeof AppCalisanlarEmployeeIdRoute
  '/daireler/$unitId': typeof AppDairelerUnitIdRoute
  '/gorevler/$taskId': typeof AppGorevlerTaskIdRoute
  '/isler/$workId': typeof AppIslerWorkIdRoute
  '/calisanlar/': typeof AppCalisanlarIndexRoute
  '/daireler/': typeof AppDairelerIndexRoute
  '/gorevler/': typeof AppGorevlerIndexRoute
  '/isler/': typeof AppIslerIndexRoute
}
export interface FileRoutesByTo {
  '/giris': typeof GirisRoute
  '/aidat': typeof AppAidatRoute
  '/aidat-ayarlari': typeof AppAidatAyarlariRoute
  '/borclar': typeof AppBorclarRoute
  '/calisan-raporu': typeof AppCalisanRaporuRoute
  '/dairem': typeof AppDairemRoute
  '/firmalar': typeof AppFirmalarRoute
  '/gelir-gider': typeof AppGelirGiderRoute
  '/giderler': typeof AppGiderlerRoute
  '/kasa': typeof AppKasaRoute
  '/kasa-ayarlari': typeof AppKasaAyarlariRoute
  '/panel': typeof AppPanelRoute
  '/raporlar': typeof AppRaporlarRoute
  '/sakinler': typeof AppSakinlerRoute
  '/sifre': typeof AppSifreRoute
  '/siteler': typeof AppSitelerRoute
  '/tahsilatlar': typeof AppTahsilatlarRoute
  '/tekrarlayan-gorevler': typeof AppTekrarlayanGorevlerRoute
  '/vardiyalar': typeof AppVardiyalarRoute
  '/davet/$token': typeof DavetTokenRoute
  '/': typeof AppIndexRoute
  '/calisanlar/$employeeId': typeof AppCalisanlarEmployeeIdRoute
  '/daireler/$unitId': typeof AppDairelerUnitIdRoute
  '/gorevler/$taskId': typeof AppGorevlerTaskIdRoute
  '/isler/$workId': typeof AppIslerWorkIdRoute
  '/calisanlar': typeof AppCalisanlarIndexRoute
  '/daireler': typeof AppDairelerIndexRoute
  '/gorevler': typeof AppGorevlerIndexRoute
  '/isler': typeof AppIslerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/giris': typeof GirisRoute
  '/_app/aidat': typeof AppAidatRoute
  '/_app/aidat-ayarlari': typeof AppAidatAyarlariRoute
  '/_app/borclar': typeof AppBorclarRoute
  '/_app/calisan-raporu': typeof AppCalisanRaporuRoute
  '/_app/dairem': typeof AppDairemRoute
  '/_app/firmalar': typeof AppFirmalarRoute
  '/_app/gelir-gider': typeof AppGelirGiderRoute
  '/_app/giderler': typeof AppGiderlerRoute
  '/_app/kasa': typeof AppKasaRoute
  '/_app/kasa-ayarlari': typeof AppKasaAyarlariRoute
  '/_app/panel': typeof AppPanelRoute
  '/_app/raporlar': typeof AppRaporlarRoute
  '/_app/sakinler': typeof AppSakinlerRoute
  '/_app/sifre': typeof AppSifreRoute
  '/_app/siteler': typeof AppSitelerRoute
  '/_app/tahsilatlar': typeof AppTahsilatlarRoute
  '/_app/tekrarlayan-gorevler': typeof AppTekrarlayanGorevlerRoute
  '/_app/vardiyalar': typeof AppVardiyalarRoute
  '/davet/$token': typeof DavetTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/calisanlar/$employeeId': typeof AppCalisanlarEmployeeIdRoute
  '/_app/daireler/$unitId': typeof AppDairelerUnitIdRoute
  '/_app/gorevler/$taskId': typeof AppGorevlerTaskIdRoute
  '/_app/isler/$workId': typeof AppIslerWorkIdRoute
  '/_app/calisanlar/': typeof AppCalisanlarIndexRoute
  '/_app/daireler/': typeof AppDairelerIndexRoute
  '/_app/gorevler/': typeof AppGorevlerIndexRoute
  '/_app/isler/': typeof AppIslerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/giris'
    | '/aidat'
    | '/aidat-ayarlari'
    | '/borclar'
    | '/calisan-raporu'
    | '/dairem'
    | '/firmalar'
    | '/gelir-gider'
    | '/giderler'
    | '/kasa'
    | '/kasa-ayarlari'
    | '/panel'
    | '/raporlar'
    | '/sakinler'
    | '/sifre'
    | '/siteler'
    | '/tahsilatlar'
    | '/tekrarlayan-gorevler'
    | '/vardiyalar'
    | '/davet/$token'
    | '/calisanlar/$employeeId'
    | '/daireler/$unitId'
    | '/gorevler/$taskId'
    | '/isler/$workId'
    | '/calisanlar/'
    | '/daireler/'
    | '/gorevler/'
    | '/isler/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/giris'
    | '/aidat'
    | '/aidat-ayarlari'
    | '/borclar'
    | '/calisan-raporu'
    | '/dairem'
    | '/firmalar'
    | '/gelir-gider'
    | '/giderler'
    | '/kasa'
    | '/kasa-ayarlari'
    | '/panel'
    | '/raporlar'
    | '/sakinler'
    | '/sifre'
    | '/siteler'
    | '/tahsilatlar'
    | '/tekrarlayan-gorevler'
    | '/vardiyalar'
    | '/davet/$token'
    | '/'
    | '/calisanlar/$employeeId'
    | '/daireler/$unitId'
    | '/gorevler/$taskId'
    | '/isler/$workId'
    | '/calisanlar'
    | '/daireler'
    | '/gorevler'
    | '/isler'
  id:
    | '__root__'
    | '/_app'
    | '/giris'
    | '/_app/aidat'
    | '/_app/aidat-ayarlari'
    | '/_app/borclar'
    | '/_app/calisan-raporu'
    | '/_app/dairem'
    | '/_app/firmalar'
    | '/_app/gelir-gider'
    | '/_app/giderler'
    | '/_app/kasa'
    | '/_app/kasa-ayarlari'
    | '/_app/panel'
    | '/_app/raporlar'
    | '/_app/sakinler'
    | '/_app/sifre'
    | '/_app/siteler'
    | '/_app/tahsilatlar'
    | '/_app/tekrarlayan-gorevler'
    | '/_app/vardiyalar'
    | '/davet/$token'
    | '/_app/'
    | '/_app/calisanlar/$employeeId'
    | '/_app/daireler/$unitId'
    | '/_app/gorevler/$taskId'
    | '/_app/isler/$workId'
    | '/_app/calisanlar/'
    | '/_app/daireler/'
    | '/_app/gorevler/'
    | '/_app/isler/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  GirisRoute: typeof GirisRoute
  DavetTokenRoute: typeof DavetTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aidat': {
      id: '/_app/aidat'
      path: '/aidat'
      fullPath: '/aidat'
      preLoaderRoute: typeof AppAidatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aidat-ayarlari': {
      id: '/_app/aidat-ayarlari'
      path: '/aidat-ayarlari'
      fullPath: '/aidat-ayarlari'
      preLoaderRoute: typeof AppAidatAyarlariRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/borclar': {
      id: '/_app/borclar'
      path: '/borclar'
      fullPath: '/borclar'
      preLoaderRoute: typeof AppBorclarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calisan-raporu': {
      id: '/_app/calisan-raporu'
      path: '/calisan-raporu'
      fullPath: '/calisan-raporu'
      preLoaderRoute: typeof AppCalisanRaporuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dairem': {
      id: '/_app/dairem'
      path: '/dairem'
      fullPath: '/dairem'
      preLoaderRoute: typeof AppDairemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/firmalar': {
      id: '/_app/firmalar'
      path: '/firmalar'
      fullPath: '/firmalar'
      preLoaderRoute: typeof AppFirmalarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gelir-gider': {
      id: '/_app/gelir-gider'
      path: '/gelir-gider'
      fullPath: '/gelir-gider'
      preLoaderRoute: typeof AppGelirGiderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/giderler': {
      id: '/_app/giderler'
      path: '/giderler'
      fullPath: '/giderler'
      preLoaderRoute: typeof AppGiderlerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kasa': {
      id: '/_app/kasa'
      path: '/kasa'
      fullPath: '/kasa'
      preLoaderRoute: typeof AppKasaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kasa-ayarlari': {
      id: '/_app/kasa-ayarlari'
      path: '/kasa-ayarlari'
      fullPath: '/kasa-ayarlari'
      preLoaderRoute: typeof AppKasaAyarlariRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/panel': {
      id: '/_app/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AppPanelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/raporlar': {
      id: '/_app/raporlar'
      path: '/raporlar'
      fullPath: '/raporlar'
      preLoaderRoute: typeof AppRaporlarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sakinler': {
      id: '/_app/sakinler'
      path: '/sakinler'
      fullPath: '/sakinler'
      preLoaderRoute: typeof AppSakinlerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sifre': {
      id: '/_app/sifre'
      path: '/sifre'
      fullPath: '/sifre'
      preLoaderRoute: typeof AppSifreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/siteler': {
      id: '/_app/siteler'
      path: '/siteler'
      fullPath: '/siteler'
      preLoaderRoute: typeof AppSitelerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tahsilatlar': {
      id: '/_app/tahsilatlar'
      path: '/tahsilatlar'
      fullPath: '/tahsilatlar'
      preLoaderRoute: typeof AppTahsilatlarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tekrarlayan-gorevler': {
      id: '/_app/tekrarlayan-gorevler'
      path: '/tekrarlayan-gorevler'
      fullPath: '/tekrarlayan-gorevler'
      preLoaderRoute: typeof AppTekrarlayanGorevlerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vardiyalar': {
      id: '/_app/vardiyalar'
      path: '/vardiyalar'
      fullPath: '/vardiyalar'
      preLoaderRoute: typeof AppVardiyalarRouteImport
      parentRoute: typeof AppRoute
    }
    '/davet/$token': {
      id: '/davet/$token'
      path: '/davet/$token'
      fullPath: '/davet/$token'
      preLoaderRoute: typeof DavetTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/calisanlar/': {
      id: '/_app/calisanlar/'
      path: '/calisanlar'
      fullPath: '/calisanlar/'
      preLoaderRoute: typeof AppCalisanlarIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calisanlar/$employeeId': {
      id: '/_app/calisanlar/$employeeId'
      path: '/calisanlar/$employeeId'
      fullPath: '/calisanlar/$employeeId'
      preLoaderRoute: typeof AppCalisanlarEmployeeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/daireler/': {
      id: '/_app/daireler/'
      path: '/daireler'
      fullPath: '/daireler/'
      preLoaderRoute: typeof AppDairelerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/daireler/$unitId': {
      id: '/_app/daireler/$unitId'
      path: '/daireler/$unitId'
      fullPath: '/daireler/$unitId'
      preLoaderRoute: typeof AppDairelerUnitIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gorevler/': {
      id: '/_app/gorevler/'
      path: '/gorevler'
      fullPath: '/gorevler/'
      preLoaderRoute: typeof AppGorevlerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gorevler/$taskId': {
      id: '/_app/gorevler/$taskId'
      path: '/gorevler/$taskId'
      fullPath: '/gorevler/$taskId'
      preLoaderRoute: typeof AppGorevlerTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/isler/': {
      id: '/_app/isler/'
      path: '/isler'
      fullPath: '/isler/'
      preLoaderRoute: typeof AppIslerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/isler/$workId': {
      id: '/_app/isler/$workId'
      path: '/isler/$workId'
      fullPath: '/isler/$workId'
      preLoaderRoute: typeof AppIslerWorkIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAidatRoute: typeof AppAidatRoute
  AppAidatAyarlariRoute: typeof AppAidatAyarlariRoute
  AppBorclarRoute: typeof AppBorclarRoute
  AppCalisanRaporuRoute: typeof AppCalisanRaporuRoute
  AppDairemRoute: typeof AppDairemRoute
  AppFirmalarRoute: typeof AppFirmalarRoute
  AppGelirGiderRoute: typeof AppGelirGiderRoute
  AppGiderlerRoute: typeof AppGiderlerRoute
  AppKasaRoute: typeof AppKasaRoute
  AppKasaAyarlariRoute: typeof AppKasaAyarlariRoute
  AppPanelRoute: typeof AppPanelRoute
  AppRaporlarRoute: typeof AppRaporlarRoute
  AppSakinlerRoute: typeof AppSakinlerRoute
  AppSifreRoute: typeof AppSifreRoute
  AppSitelerRoute: typeof AppSitelerRoute
  AppTahsilatlarRoute: typeof AppTahsilatlarRoute
  AppTekrarlayanGorevlerRoute: typeof AppTekrarlayanGorevlerRoute
  AppVardiyalarRoute: typeof AppVardiyalarRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCalisanlarEmployeeIdRoute: typeof AppCalisanlarEmployeeIdRoute
  AppDairelerUnitIdRoute: typeof AppDairelerUnitIdRoute
  AppGorevlerTaskIdRoute: typeof AppGorevlerTaskIdRoute
  AppIslerWorkIdRoute: typeof AppIslerWorkIdRoute
  AppCalisanlarIndexRoute: typeof AppCalisanlarIndexRoute
  AppDairelerIndexRoute: typeof AppDairelerIndexRoute
  AppGorevlerIndexRoute: typeof AppGorevlerIndexRoute
  AppIslerIndexRoute: typeof AppIslerIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAidatRoute: AppAidatRoute,
  AppAidatAyarlariRoute: AppAidatAyarlariRoute,
  AppBorclarRoute: AppBorclarRoute,
  AppCalisanRaporuRoute: AppCalisanRaporuRoute,
  AppDairemRoute: AppDairemRoute,
  AppFirmalarRoute: AppFirmalarRoute,
  AppGelirGiderRoute: AppGelirGiderRoute,
  AppGiderlerRoute: AppGiderlerRoute,
  AppKasaRoute: AppKasaRoute,
  AppKasaAyarlariRoute: AppKasaAyarlariRoute,
  AppPanelRoute: AppPanelRoute,
  AppRaporlarRoute: AppRaporlarRoute,
  AppSakinlerRoute: AppSakinlerRoute,
  AppSifreRoute: AppSifreRoute,
  AppSitelerRoute: AppSitelerRoute,
  AppTahsilatlarRoute: AppTahsilatlarRoute,
  AppTekrarlayanGorevlerRoute: AppTekrarlayanGorevlerRoute,
  AppVardiyalarRoute: AppVardiyalarRoute,
  AppIndexRoute: AppIndexRoute,
  AppCalisanlarEmployeeIdRoute: AppCalisanlarEmployeeIdRoute,
  AppDairelerUnitIdRoute: AppDairelerUnitIdRoute,
  AppGorevlerTaskIdRoute: AppGorevlerTaskIdRoute,
  AppIslerWorkIdRoute: AppIslerWorkIdRoute,
  AppCalisanlarIndexRoute: AppCalisanlarIndexRoute,
  AppDairelerIndexRoute: AppDairelerIndexRoute,
  AppGorevlerIndexRoute: AppGorevlerIndexRoute,
  AppIslerIndexRoute: AppIslerIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  GirisRoute: GirisRoute,
  DavetTokenRoute: DavetTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
