/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAidatRouteImport } from './routes/_app/aidat'
import { Route as AppAidatAyarlariRouteImport } from './routes/_app/aidat-ayarlari'
import { Route as AppBankaHareketleriRouteImport } from './routes/_app/banka-hareketleri'
import { Route as AppBildirimlerRouteImport } from './routes/_app/bildirimler'
import { Route as AppBorclarRouteImport } from './routes/_app/borclar'
import { Route as AppCalisanRaporuRouteImport } from './routes/_app/calisan-raporu'
import { Route as AppDairemRouteImport } from './routes/_app/dairem'
import { Route as AppExcelAktarmaRouteImport } from './routes/_app/excel-aktarma'
import { Route as AppFirmalarRouteImport } from './routes/_app/firmalar'
import { Route as AppGelirGiderRouteImport } from './routes/_app/gelir-gider'
import { Route as AppGiderlerRouteImport } from './routes/_app/giderler'
import { Route as AppIslemGecmisiRouteImport } from './routes/_app/islem-gecmisi'
import { Route as AppKasaRouteImport } from './routes/_app/kasa'
import { Route as AppKasaAyarlariRouteImport } from './routes/_app/kasa-ayarlari'
import { Route as AppMarkaRouteImport } from './routes/_app/marka'
import { Route as AppMesajAyarlariRouteImport } from './routes/_app/mesaj-ayarlari'
import { Route as AppPanelRouteImport } from './routes/_app/panel'
import { Route as AppRaporlarRouteImport } from './routes/_app/raporlar'
import { Route as AppSakinlerRouteImport } from './routes/_app/sakinler'
import { Route as AppSifreRouteImport } from './routes/_app/sifre'
import { Route as AppSitelerRouteImport } from './routes/_app/siteler'
import { Route as AppTahsilatlarRouteImport } from './routes/_app/tahsilatlar'
import { Route as AppTekrarlayanGorevlerRouteImport } from './routes/_app/tekrarlayan-gorevler'
import { Route as AppVardiyalarRouteImport } from './routes/_app/vardiyalar'
import { Route as AppYetkililerRouteImport } from './routes/_app/yetkililer'
import { Route as DavetTokenRouteImport } from './routes/davet.$token'
import { Route as SifreYenileTokenRouteImport } from './routes/sifre-yenile.$token'
import { Route as AppButceIndexRouteImport } from './routes/_app/butce/index'
import { Route as AppButceBudgetIdRouteImport } from './routes/_app/butce/$budgetId'
import { Route as AppCalisanlarIndexRouteImport } from './routes/_app/calisanlar/index'
import { Route as AppCalisanlarEmployeeIdRouteImport } from './routes/_app/calisanlar/$employeeId'
import { Route as AppDairelerIndexRouteImport } from './routes/_app/daireler/index'
import { Route as AppDairelerUnitIdRouteImport } from './routes/_app/daireler/$unitId'
import { Route as AppDuyurularIndexRouteImport } from './routes/_app/duyurular/index'
import { Route as AppDuyurularAnnouncementIdRouteImport } from './routes/_app/duyurular/$announcementId'
import { Route as AppGenelKurulIndexRouteImport } from './routes/_app/genel-kurul/index'
import { Route as AppGenelKurulMeetingIdRouteImport } from './routes/_app/genel-kurul/$meetingId'
import { Route as AppGorevlerIndexRouteImport } from './routes/_app/gorevler/index'
import { Route as AppGorevlerTaskIdRouteImport } from './routes/_app/gorevler/$taskId'
import { Route as AppIslerIndexRouteImport } from './routes/_app/isler/index'
import { Route as AppIslerWorkIdRouteImport } from './routes/_app/isler/$workId'
import { Route as AppMesajlarIndexRouteImport } from './routes/_app/mesajlar/index'
import { Route as AppMesajlarCampaignIdRouteImport } from './routes/_app/mesajlar/$campaignId'
import { Route as AppMesajlarYeniRouteImport } from './routes/_app/mesajlar/yeni'
import { Route as AppOdemeSonucRouteImport } from './routes/_app/odeme/sonuc'
import { Route as AppTaleplerIndexRouteImport } from './routes/_app/talepler/index'
import { Route as AppTaleplerRequestIdRouteImport } from './routes/_app/talepler/$requestId'
import { Route as AppTaleplerimIndexRouteImport } from './routes/_app/taleplerim/index'
import { Route as AppTaleplerimRequestIdRouteImport } from './routes/_app/taleplerim/$requestId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAidatRoute = AppAidatRouteImport.update({
  id: '/aidat',
  path: '/aidat',
  getParentRoute: () => AppRoute,
} as any)
const AppAidatAyarlariRoute = AppAidatAyarlariRouteImport.update({
  id: '/aidat-ayarlari',
  path: '/aidat-ayarlari',
  getParentRoute: () => AppRoute,
} as any)
const AppBankaHareketleriRoute = AppBankaHareketleriRouteImport.update({
  id: '/banka-hareketleri',
  path: '/banka-hareketleri',
  getParentRoute: () => AppRoute,
} as any)
const AppBildirimlerRoute = AppBildirimlerRouteImport.update({
  id: '/bildirimler',
  path: '/bildirimler',
  getParentRoute: () => AppRoute,
} as any)
const AppBorclarRoute = AppBorclarRouteImport.update({
  id: '/borclar',
  path: '/borclar',
  getParentRoute: () => AppRoute,
} as any)
const AppCalisanRaporuRoute = AppCalisanRaporuRouteImport.update({
  id: '/calisan-raporu',
  path: '/calisan-raporu',
  getParentRoute: () => AppRoute,
} as any)
const AppDairemRoute = AppDairemRouteImport.update({
  id: '/dairem',
  path: '/dairem',
  getParentRoute: () => AppRoute,
} as any)
const AppExcelAktarmaRoute = AppExcelAktarmaRouteImport.update({
  id: '/excel-aktarma',
  path: '/excel-aktarma',
  getParentRoute: () => AppRoute,
} as any)
const AppFirmalarRoute = AppFirmalarRouteImport.update({
  id: '/firmalar',
  path: '/firmalar',
  getParentRoute: () => AppRoute,
} as any)
const AppGelirGiderRoute = AppGelirGiderRouteImport.update({
  id: '/gelir-gider',
  path: '/gelir-gider',
  getParentRoute: () => AppRoute,
} as any)
const AppGiderlerRoute = AppGiderlerRouteImport.update({
  id: '/giderler',
  path: '/giderler',
  getParentRoute: () => AppRoute,
} as any)
const AppIslemGecmisiRoute = AppIslemGecmisiRouteImport.update({
  id: '/islem-gecmisi',
  path: '/islem-gecmisi',
  getParentRoute: () => AppRoute,
} as any)
const AppKasaRoute = AppKasaRouteImport.update({
  id: '/kasa',
  path: '/kasa',
  getParentRoute: () => AppRoute,
} as any)
const AppKasaAyarlariRoute = AppKasaAyarlariRouteImport.update({
  id: '/kasa-ayarlari',
  path: '/kasa-ayarlari',
  getParentRoute: () => AppRoute,
} as any)
const AppMarkaRoute = AppMarkaRouteImport.update({
  id: '/marka',
  path: '/marka',
  getParentRoute: () => AppRoute,
} as any)
const AppMesajAyarlariRoute = AppMesajAyarlariRouteImport.update({
  id: '/mesaj-ayarlari',
  path: '/mesaj-ayarlari',
  getParentRoute: () => AppRoute,
} as any)
const AppPanelRoute = AppPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AppRoute,
} as any)
const AppRaporlarRoute = AppRaporlarRouteImport.update({
  id: '/raporlar',
  path: '/raporlar',
  getParentRoute: () => AppRoute,
} as any)
const AppSakinlerRoute = AppSakinlerRouteImport.update({
  id: '/sakinler',
  path: '/sakinler',
  getParentRoute: () => AppRoute,
} as any)
const AppSifreRoute = AppSifreRouteImport.update({
  id: '/sifre',
  path: '/sifre',
  getParentRoute: () => AppRoute,
} as any)
const AppSitelerRoute = AppSitelerRouteImport.update({
  id: '/siteler',
  path: '/siteler',
  getParentRoute: () => AppRoute,
} as any)
const AppTahsilatlarRoute = AppTahsilatlarRouteImport.update({
  id: '/tahsilatlar',
  path: '/tahsilatlar',
  getParentRoute: () => AppRoute,
} as any)
const AppTekrarlayanGorevlerRoute = AppTekrarlayanGorevlerRouteImport.update({
  id: '/tekrarlayan-gorevler',
  path: '/tekrarlayan-gorevler',
  getParentRoute: () => AppRoute,
} as any)
const AppVardiyalarRoute = AppVardiyalarRouteImport.update({
  id: '/vardiyalar',
  path: '/vardiyalar',
  getParentRoute: () => AppRoute,
} as any)
const AppYetkililerRoute = AppYetkililerRouteImport.update({
  id: '/yetkililer',
  path: '/yetkililer',
  getParentRoute: () => AppRoute,
} as any)
const DavetTokenRoute = DavetTokenRouteImport.update({
  id: '/davet/$token',
  path: '/davet/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SifreYenileTokenRoute = SifreYenileTokenRouteImport.update({
  id: '/sifre-yenile/$token',
  path: '/sifre-yenile/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppButceIndexRoute = AppButceIndexRouteImport.update({
  id: '/butce/',
  path: '/butce/',
  getParentRoute: () => AppRoute,
} as any)
const AppButceBudgetIdRoute = AppButceBudgetIdRouteImport.update({
  id: '/butce/$budgetId',
  path: '/butce/$budgetId',
  getParentRoute: () => AppRoute,
} as any)
const AppCalisanlarIndexRoute = AppCalisanlarIndexRouteImport.update({
  id: '/calisanlar/',
  path: '/calisanlar/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalisanlarEmployeeIdRoute = AppCalisanlarEmployeeIdRouteImport.update({
  id: '/calisanlar/$employeeId',
  path: '/calisanlar/$employeeId',
  getParentRoute: () => AppRoute,
} as any)
const AppDairelerIndexRoute = AppDairelerIndexRouteImport.update({
  id: '/daireler/',
  path: '/daireler/',
  getParentRoute: () => AppRoute,
} as any)
const AppDairelerUnitIdRoute = AppDairelerUnitIdRouteImport.update({
  id: '/daireler/$unitId',
  path: '/daireler/$unitId',
  getParentRoute: () => AppRoute,
} as any)
const AppDuyurularIndexRoute = AppDuyurularIndexRouteImport.update({
  id: '/duyurular/',
  path: '/duyurular/',
  getParentRoute: () => AppRoute,
} as any)
const AppDuyurularAnnouncementIdRoute =
  AppDuyurularAnnouncementIdRouteImport.update({
    id: '/duyurular/$announcementId',
    path: '/duyurular/$announcementId',
    getParentRoute: () => AppRoute,
  } as any)
const AppGenelKurulIndexRoute = AppGenelKurulIndexRouteImport.update({
  id: '/genel-kurul/',
  path: '/genel-kurul/',
  getParentRoute: () => AppRoute,
} as any)
const AppGenelKurulMeetingIdRoute = AppGenelKurulMeetingIdRouteImport.update({
  id: '/genel-kurul/$meetingId',
  path: '/genel-kurul/$meetingId',
  getParentRoute: () => AppRoute,
} as any)
const AppGorevlerIndexRoute = AppGorevlerIndexRouteImport.update({
  id: '/gorevler/',
  path: '/gorevler/',
  getParentRoute: () => AppRoute,
} as any)
const AppGorevlerTaskIdRoute = AppGorevlerTaskIdRouteImport.update({
  id: '/gorevler/$taskId',
  path: '/gorevler/$taskId',
  getParentRoute: () => AppRoute,
} as any)
const AppIslerIndexRoute = AppIslerIndexRouteImport.update({
  id: '/isler/',
  path: '/isler/',
  getParentRoute: () => AppRoute,
} as any)
const AppIslerWorkIdRoute = AppIslerWorkIdRouteImport.update({
  id: '/isler/$workId',
  path: '/isler/$workId',
  getParentRoute: () => AppRoute,
} as any)
const AppMesajlarIndexRoute = AppMesajlarIndexRouteImport.update({
  id: '/mesajlar/',
  path: '/mesajlar/',
  getParentRoute: () => AppRoute,
} as any)
const AppMesajlarCampaignIdRoute = AppMesajlarCampaignIdRouteImport.update({
  id: '/mesajlar/$campaignId',
  path: '/mesajlar/$campaignId',
  getParentRoute: () => AppRoute,
} as any)
const AppMesajlarYeniRoute = AppMesajlarYeniRouteImport.update({
  id: '/mesajlar/yeni',
  path: '/mesajlar/yeni',
  getParentRoute: () => AppRoute,
} as any)
const AppOdemeSonucRoute = AppOdemeSonucRouteImport.update({
  id: '/odeme/sonuc',
  path: '/odeme/sonuc',
  getParentRoute: () => AppRoute,
} as any)
const AppTaleplerIndexRoute = AppTaleplerIndexRouteImport.update({
  id: '/talepler/',
  path: '/talepler/',
  getParentRoute: () => AppRoute,
} as any)
const AppTaleplerRequestIdRoute = AppTaleplerRequestIdRouteImport.update({
  id: '/talepler/$requestId',
  path: '/talepler/$requestId',
  getParentRoute: () => AppRoute,
} as any)
const AppTaleplerimIndexRoute = AppTaleplerimIndexRouteImport.update({
  id: '/taleplerim/',
  path: '/taleplerim/',
  getParentRoute: () => AppRoute,
} as any)
const AppTaleplerimRequestIdRoute = AppTaleplerimRequestIdRouteImport.update({
  id: '/taleplerim/$requestId',
  path: '/taleplerim/$requestId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/giris': typeof GirisRoute
  '/aidat': typeof AppAidatRoute
  '/aidat-ayarlari': typeof AppAidatAyarlariRoute
  '/banka-hareketleri': typeof AppBankaHareketleriRoute
  '/bildirimler': typeof AppBildirimlerRoute
  '/borclar': typeof AppBorclarRoute
  '/calisan-raporu': typeof AppCalisanRaporuRoute
  '/dairem': typeof AppDairemRoute
  '/excel-aktarma': typeof AppExcelAktarmaRoute
  '/firmalar': typeof AppFirmalarRoute
  '/gelir-gider': typeof AppGelirGiderRoute
  '/giderler': typeof AppGiderlerRoute
  '/islem-gecmisi': typeof AppIslemGecmisiRoute
  '/kasa': typeof AppKasaRoute
  '/kasa-ayarlari': typeof AppKasaAyarlariRoute
  '/marka': typeof AppMarkaRoute
  '/mesaj-ayarlari': typeof AppMesajAyarlariRoute
  '/panel': typeof AppPanelRoute
  '/raporlar': typeof AppRaporlarRoute
  '/sakinler': typeof AppSakinlerRoute
  '/sifre': typeof AppSifreRoute
  '/siteler': typeof AppSitelerRoute
  '/tahsilatlar': typeof AppTahsilatlarRoute
  '/tekrarlayan-gorevler': typeof AppTekrarlayanGorevlerRoute
  '/vardiyalar': typeof AppVardiyalarRoute
  '/yetkililer': typeof AppYetkililerRoute
  '/davet/$token': typeof DavetTokenRoute
  '/sifre-yenile/$token': typeof SifreYenileTokenRoute
  '/butce/$budgetId': typeof AppButceBudgetIdRoute
  '/calisanlar/$employeeId': typeof AppCalisanlarEmployeeIdRoute
  '/daireler/$unitId': typeof AppDairelerUnitIdRoute
  '/duyurular/$announcementId': typeof AppDuyurularAnnouncementIdRoute
  '/genel-kurul/$meetingId': typeof AppGenelKurulMeetingIdRoute
  '/gorevler/$taskId': typeof AppGorevlerTaskIdRoute
  '/isler/$workId': typeof AppIslerWorkIdRoute
  '/mesajlar/$campaignId': typeof AppMesajlarCampaignIdRoute
  '/mesajlar/yeni': typeof AppMesajlarYeniRoute
  '/odeme/sonuc': typeof AppOdemeSonucRoute
  '/talepler/$requestId': typeof AppTaleplerRequestIdRoute
  '/taleplerim/$requestId': typeof AppTaleplerimRequestIdRoute
  '/butce/': typeof AppButceIndexRoute
  '/calisanlar/': typeof AppCalisanlarIndexRoute
  '/daireler/': typeof AppDairelerIndexRoute
  '/duyurular/': typeof AppDuyurularIndexRoute
  '/genel-kurul/': typeof AppGenelKurulIndexRoute
  '/gorevler/': typeof AppGorevlerIndexRoute
  '/isler/': typeof AppIslerIndexRoute
  '/mesajlar/': typeof AppMesajlarIndexRoute
  '/talepler/': typeof AppTaleplerIndexRoute
  '/taleplerim/': typeof AppTaleplerimIndexRoute
}
export interface FileRoutesByTo {
  '/giris': typeof GirisRoute
  '/aidat': typeof AppAidatRoute
  '/aidat-ayarlari': typeof AppAidatAyarlariRoute
  '/banka-hareketleri': typeof AppBankaHareketleriRoute
  '/bildirimler': typeof AppBildirimlerRoute
  '/borclar': typeof AppBorclarRoute
  '/calisan-raporu': typeof AppCalisanRaporuRoute
  '/dairem': typeof AppDairemRoute
  '/excel-aktarma': typeof AppExcelAktarmaRoute
  '/firmalar': typeof AppFirmalarRoute
  '/gelir-gider': typeof AppGelirGiderRoute
  '/giderler': typeof AppGiderlerRoute
  '/islem-gecmisi': typeof AppIslemGecmisiRoute
  '/kasa': typeof AppKasaRoute
  '/kasa-ayarlari': typeof AppKasaAyarlariRoute
  '/marka': typeof AppMarkaRoute
  '/mesaj-ayarlari': typeof AppMesajAyarlariRoute
  '/panel': typeof AppPanelRoute
  '/raporlar': typeof AppRaporlarRoute
  '/sakinler': typeof AppSakinlerRoute
  '/sifre': typeof AppSifreRoute
  '/siteler': typeof AppSitelerRoute
  '/tahsilatlar': typeof AppTahsilatlarRoute
  '/tekrarlayan-gorevler': typeof AppTekrarlayanGorevlerRoute
  '/vardiyalar': typeof AppVardiyalarRoute
  '/yetkililer': typeof AppYetkililerRoute
  '/davet/$token': typeof DavetTokenRoute
  '/sifre-yenile/$token': typeof SifreYenileTokenRoute
  '/': typeof AppIndexRoute
  '/butce/$budgetId': typeof AppButceBudgetIdRoute
  '/calisanlar/$employeeId': typeof AppCalisanlarEmployeeIdRoute
  '/daireler/$unitId': typeof AppDairelerUnitIdRoute
  '/duyurular/$announcementId': typeof AppDuyurularAnnouncementIdRoute
  '/genel-kurul/$meetingId': typeof AppGenelKurulMeetingIdRoute
  '/gorevler/$taskId': typeof AppGorevlerTaskIdRoute
  '/isler/$workId': typeof AppIslerWorkIdRoute
  '/mesajlar/$campaignId': typeof AppMesajlarCampaignIdRoute
  '/mesajlar/yeni': typeof AppMesajlarYeniRoute
  '/odeme/sonuc': typeof AppOdemeSonucRoute
  '/talepler/$requestId': typeof AppTaleplerRequestIdRoute
  '/taleplerim/$requestId': typeof AppTaleplerimRequestIdRoute
  '/butce': typeof AppButceIndexRoute
  '/calisanlar': typeof AppCalisanlarIndexRoute
  '/daireler': typeof AppDairelerIndexRoute
  '/duyurular': typeof AppDuyurularIndexRoute
  '/genel-kurul': typeof AppGenelKurulIndexRoute
  '/gorevler': typeof AppGorevlerIndexRoute
  '/isler': typeof AppIslerIndexRoute
  '/mesajlar': typeof AppMesajlarIndexRoute
  '/talepler': typeof AppTaleplerIndexRoute
  '/taleplerim': typeof AppTaleplerimIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/giris': typeof GirisRoute
  '/_app/aidat': typeof AppAidatRoute
  '/_app/aidat-ayarlari': typeof AppAidatAyarlariRoute
  '/_app/banka-hareketleri': typeof AppBankaHareketleriRoute
  '/_app/bildirimler': typeof AppBildirimlerRoute
  '/_app/borclar': typeof AppBorclarRoute
  '/_app/calisan-raporu': typeof AppCalisanRaporuRoute
  '/_app/dairem': typeof AppDairemRoute
  '/_app/excel-aktarma': typeof AppExcelAktarmaRoute
  '/_app/firmalar': typeof AppFirmalarRoute
  '/_app/gelir-gider': typeof AppGelirGiderRoute
  '/_app/giderler': typeof AppGiderlerRoute
  '/_app/islem-gecmisi': typeof AppIslemGecmisiRoute
  '/_app/kasa': typeof AppKasaRoute
  '/_app/kasa-ayarlari': typeof AppKasaAyarlariRoute
  '/_app/marka': typeof AppMarkaRoute
  '/_app/mesaj-ayarlari': typeof AppMesajAyarlariRoute
  '/_app/panel': typeof AppPanelRoute
  '/_app/raporlar': typeof AppRaporlarRoute
  '/_app/sakinler': typeof AppSakinlerRoute
  '/_app/sifre': typeof AppSifreRoute
  '/_app/siteler': typeof AppSitelerRoute
  '/_app/tahsilatlar': typeof AppTahsilatlarRoute
  '/_app/tekrarlayan-gorevler': typeof AppTekrarlayanGorevlerRoute
  '/_app/vardiyalar': typeof AppVardiyalarRoute
  '/_app/yetkililer': typeof AppYetkililerRoute
  '/davet/$token': typeof DavetTokenRoute
  '/sifre-yenile/$token': typeof SifreYenileTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/butce/$budgetId': typeof AppButceBudgetIdRoute
  '/_app/calisanlar/$employeeId': typeof AppCalisanlarEmployeeIdRoute
  '/_app/daireler/$unitId': typeof AppDairelerUnitIdRoute
  '/_app/duyurular/$announcementId': typeof AppDuyurularAnnouncementIdRoute
  '/_app/genel-kurul/$meetingId': typeof AppGenelKurulMeetingIdRoute
  '/_app/gorevler/$taskId': typeof AppGorevlerTaskIdRoute
  '/_app/isler/$workId': typeof AppIslerWorkIdRoute
  '/_app/mesajlar/$campaignId': typeof AppMesajlarCampaignIdRoute
  '/_app/mesajlar/yeni': typeof AppMesajlarYeniRoute
  '/_app/odeme/sonuc': typeof AppOdemeSonucRoute
  '/_app/talepler/$requestId': typeof AppTaleplerRequestIdRoute
  '/_app/taleplerim/$requestId': typeof AppTaleplerimRequestIdRoute
  '/_app/butce/': typeof AppButceIndexRoute
  '/_app/calisanlar/': typeof AppCalisanlarIndexRoute
  '/_app/daireler/': typeof AppDairelerIndexRoute
  '/_app/duyurular/': typeof AppDuyurularIndexRoute
  '/_app/genel-kurul/': typeof AppGenelKurulIndexRoute
  '/_app/gorevler/': typeof AppGorevlerIndexRoute
  '/_app/isler/': typeof AppIslerIndexRoute
  '/_app/mesajlar/': typeof AppMesajlarIndexRoute
  '/_app/talepler/': typeof AppTaleplerIndexRoute
  '/_app/taleplerim/': typeof AppTaleplerimIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/giris'
    | '/aidat'
    | '/aidat-ayarlari'
    | '/banka-hareketleri'
    | '/bildirimler'
    | '/borclar'
    | '/calisan-raporu'
    | '/dairem'
    | '/excel-aktarma'
    | '/firmalar'
    | '/gelir-gider'
    | '/giderler'
    | '/islem-gecmisi'
    | '/kasa'
    | '/kasa-ayarlari'
    | '/marka'
    | '/mesaj-ayarlari'
    | '/panel'
    | '/raporlar'
    | '/sakinler'
    | '/sifre'
    | '/siteler'
    | '/tahsilatlar'
    | '/tekrarlayan-gorevler'
    | '/vardiyalar'
    | '/yetkililer'
    | '/davet/$token'
    | '/sifre-yenile/$token'
    | '/butce/$budgetId'
    | '/calisanlar/$employeeId'
    | '/daireler/$unitId'
    | '/duyurular/$announcementId'
    | '/genel-kurul/$meetingId'
    | '/gorevler/$taskId'
    | '/isler/$workId'
    | '/mesajlar/$campaignId'
    | '/mesajlar/yeni'
    | '/odeme/sonuc'
    | '/talepler/$requestId'
    | '/taleplerim/$requestId'
    | '/butce/'
    | '/calisanlar/'
    | '/daireler/'
    | '/duyurular/'
    | '/genel-kurul/'
    | '/gorevler/'
    | '/isler/'
    | '/mesajlar/'
    | '/talepler/'
    | '/taleplerim/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/giris'
    | '/aidat'
    | '/aidat-ayarlari'
    | '/banka-hareketleri'
    | '/bildirimler'
    | '/borclar'
    | '/calisan-raporu'
    | '/dairem'
    | '/excel-aktarma'
    | '/firmalar'
    | '/gelir-gider'
    | '/giderler'
    | '/islem-gecmisi'
    | '/kasa'
    | '/kasa-ayarlari'
    | '/marka'
    | '/mesaj-ayarlari'
    | '/panel'
    | '/raporlar'
    | '/sakinler'
    | '/sifre'
    | '/siteler'
    | '/tahsilatlar'
    | '/tekrarlayan-gorevler'
    | '/vardiyalar'
    | '/yetkililer'
    | '/davet/$token'
    | '/sifre-yenile/$token'
    | '/'
    | '/butce/$budgetId'
    | '/calisanlar/$employeeId'
    | '/daireler/$unitId'
    | '/duyurular/$announcementId'
    | '/genel-kurul/$meetingId'
    | '/gorevler/$taskId'
    | '/isler/$workId'
    | '/mesajlar/$campaignId'
    | '/mesajlar/yeni'
    | '/odeme/sonuc'
    | '/talepler/$requestId'
    | '/taleplerim/$requestId'
    | '/butce'
    | '/calisanlar'
    | '/daireler'
    | '/duyurular'
    | '/genel-kurul'
    | '/gorevler'
    | '/isler'
    | '/mesajlar'
    | '/talepler'
    | '/taleplerim'
  id:
    | '__root__'
    | '/_app'
    | '/giris'
    | '/_app/aidat'
    | '/_app/aidat-ayarlari'
    | '/_app/banka-hareketleri'
    | '/_app/bildirimler'
    | '/_app/borclar'
    | '/_app/calisan-raporu'
    | '/_app/dairem'
    | '/_app/excel-aktarma'
    | '/_app/firmalar'
    | '/_app/gelir-gider'
    | '/_app/giderler'
    | '/_app/islem-gecmisi'
    | '/_app/kasa'
    | '/_app/kasa-ayarlari'
    | '/_app/marka'
    | '/_app/mesaj-ayarlari'
    | '/_app/panel'
    | '/_app/raporlar'
    | '/_app/sakinler'
    | '/_app/sifre'
    | '/_app/siteler'
    | '/_app/tahsilatlar'
    | '/_app/tekrarlayan-gorevler'
    | '/_app/vardiyalar'
    | '/_app/yetkililer'
    | '/davet/$token'
    | '/sifre-yenile/$token'
    | '/_app/'
    | '/_app/butce/$budgetId'
    | '/_app/calisanlar/$employeeId'
    | '/_app/daireler/$unitId'
    | '/_app/duyurular/$announcementId'
    | '/_app/genel-kurul/$meetingId'
    | '/_app/gorevler/$taskId'
    | '/_app/isler/$workId'
    | '/_app/mesajlar/$campaignId'
    | '/_app/mesajlar/yeni'
    | '/_app/odeme/sonuc'
    | '/_app/talepler/$requestId'
    | '/_app/taleplerim/$requestId'
    | '/_app/butce/'
    | '/_app/calisanlar/'
    | '/_app/daireler/'
    | '/_app/duyurular/'
    | '/_app/genel-kurul/'
    | '/_app/gorevler/'
    | '/_app/isler/'
    | '/_app/mesajlar/'
    | '/_app/talepler/'
    | '/_app/taleplerim/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  GirisRoute: typeof GirisRoute
  DavetTokenRoute: typeof DavetTokenRoute
  SifreYenileTokenRoute: typeof SifreYenileTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aidat': {
      id: '/_app/aidat'
      path: '/aidat'
      fullPath: '/aidat'
      preLoaderRoute: typeof AppAidatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aidat-ayarlari': {
      id: '/_app/aidat-ayarlari'
      path: '/aidat-ayarlari'
      fullPath: '/aidat-ayarlari'
      preLoaderRoute: typeof AppAidatAyarlariRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/banka-hareketleri': {
      id: '/_app/banka-hareketleri'
      path: '/banka-hareketleri'
      fullPath: '/banka-hareketleri'
      preLoaderRoute: typeof AppBankaHareketleriRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bildirimler': {
      id: '/_app/bildirimler'
      path: '/bildirimler'
      fullPath: '/bildirimler'
      preLoaderRoute: typeof AppBildirimlerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/borclar': {
      id: '/_app/borclar'
      path: '/borclar'
      fullPath: '/borclar'
      preLoaderRoute: typeof AppBorclarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calisan-raporu': {
      id: '/_app/calisan-raporu'
      path: '/calisan-raporu'
      fullPath: '/calisan-raporu'
      preLoaderRoute: typeof AppCalisanRaporuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dairem': {
      id: '/_app/dairem'
      path: '/dairem'
      fullPath: '/dairem'
      preLoaderRoute: typeof AppDairemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/excel-aktarma': {
      id: '/_app/excel-aktarma'
      path: '/excel-aktarma'
      fullPath: '/excel-aktarma'
      preLoaderRoute: typeof AppExcelAktarmaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/firmalar': {
      id: '/_app/firmalar'
      path: '/firmalar'
      fullPath: '/firmalar'
      preLoaderRoute: typeof AppFirmalarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gelir-gider': {
      id: '/_app/gelir-gider'
      path: '/gelir-gider'
      fullPath: '/gelir-gider'
      preLoaderRoute: typeof AppGelirGiderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/giderler': {
      id: '/_app/giderler'
      path: '/giderler'
      fullPath: '/giderler'
      preLoaderRoute: typeof AppGiderlerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/islem-gecmisi': {
      id: '/_app/islem-gecmisi'
      path: '/islem-gecmisi'
      fullPath: '/islem-gecmisi'
      preLoaderRoute: typeof AppIslemGecmisiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kasa': {
      id: '/_app/kasa'
      path: '/kasa'
      fullPath: '/kasa'
      preLoaderRoute: typeof AppKasaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kasa-ayarlari': {
      id: '/_app/kasa-ayarlari'
      path: '/kasa-ayarlari'
      fullPath: '/kasa-ayarlari'
      preLoaderRoute: typeof AppKasaAyarlariRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marka': {
      id: '/_app/marka'
      path: '/marka'
      fullPath: '/marka'
      preLoaderRoute: typeof AppMarkaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mesaj-ayarlari': {
      id: '/_app/mesaj-ayarlari'
      path: '/mesaj-ayarlari'
      fullPath: '/mesaj-ayarlari'
      preLoaderRoute: typeof AppMesajAyarlariRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/panel': {
      id: '/_app/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AppPanelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/raporlar': {
      id: '/_app/raporlar'
      path: '/raporlar'
      fullPath: '/raporlar'
      preLoaderRoute: typeof AppRaporlarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sakinler': {
      id: '/_app/sakinler'
      path: '/sakinler'
      fullPath: '/sakinler'
      preLoaderRoute: typeof AppSakinlerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sifre': {
      id: '/_app/sifre'
      path: '/sifre'
      fullPath: '/sifre'
      preLoaderRoute: typeof AppSifreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/siteler': {
      id: '/_app/siteler'
      path: '/siteler'
      fullPath: '/siteler'
      preLoaderRoute: typeof AppSitelerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tahsilatlar': {
      id: '/_app/tahsilatlar'
      path: '/tahsilatlar'
      fullPath: '/tahsilatlar'
      preLoaderRoute: typeof AppTahsilatlarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tekrarlayan-gorevler': {
      id: '/_app/tekrarlayan-gorevler'
      path: '/tekrarlayan-gorevler'
      fullPath: '/tekrarlayan-gorevler'
      preLoaderRoute: typeof AppTekrarlayanGorevlerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vardiyalar': {
      id: '/_app/vardiyalar'
      path: '/vardiyalar'
      fullPath: '/vardiyalar'
      preLoaderRoute: typeof AppVardiyalarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/yetkililer': {
      id: '/_app/yetkililer'
      path: '/yetkililer'
      fullPath: '/yetkililer'
      preLoaderRoute: typeof AppYetkililerRouteImport
      parentRoute: typeof AppRoute
    }
    '/davet/$token': {
      id: '/davet/$token'
      path: '/davet/$token'
      fullPath: '/davet/$token'
      preLoaderRoute: typeof DavetTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sifre-yenile/$token': {
      id: '/sifre-yenile/$token'
      path: '/sifre-yenile/$token'
      fullPath: '/sifre-yenile/$token'
      preLoaderRoute: typeof SifreYenileTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/butce/': {
      id: '/_app/butce/'
      path: '/butce'
      fullPath: '/butce/'
      preLoaderRoute: typeof AppButceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/butce/$budgetId': {
      id: '/_app/butce/$budgetId'
      path: '/butce/$budgetId'
      fullPath: '/butce/$budgetId'
      preLoaderRoute: typeof AppButceBudgetIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calisanlar/': {
      id: '/_app/calisanlar/'
      path: '/calisanlar'
      fullPath: '/calisanlar/'
      preLoaderRoute: typeof AppCalisanlarIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calisanlar/$employeeId': {
      id: '/_app/calisanlar/$employeeId'
      path: '/calisanlar/$employeeId'
      fullPath: '/calisanlar/$employeeId'
      preLoaderRoute: typeof AppCalisanlarEmployeeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/daireler/': {
      id: '/_app/daireler/'
      path: '/daireler'
      fullPath: '/daireler/'
      preLoaderRoute: typeof AppDairelerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/daireler/$unitId': {
      id: '/_app/daireler/$unitId'
      path: '/daireler/$unitId'
      fullPath: '/daireler/$unitId'
      preLoaderRoute: typeof AppDairelerUnitIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/duyurular/': {
      id: '/_app/duyurular/'
      path: '/duyurular'
      fullPath: '/duyurular/'
      preLoaderRoute: typeof AppDuyurularIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/duyurular/$announcementId': {
      id: '/_app/duyurular/$announcementId'
      path: '/duyurular/$announcementId'
      fullPath: '/duyurular/$announcementId'
      preLoaderRoute: typeof AppDuyurularAnnouncementIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/genel-kurul/': {
      id: '/_app/genel-kurul/'
      path: '/genel-kurul'
      fullPath: '/genel-kurul/'
      preLoaderRoute: typeof AppGenelKurulIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/genel-kurul/$meetingId': {
      id: '/_app/genel-kurul/$meetingId'
      path: '/genel-kurul/$meetingId'
      fullPath: '/genel-kurul/$meetingId'
      preLoaderRoute: typeof AppGenelKurulMeetingIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gorevler/': {
      id: '/_app/gorevler/'
      path: '/gorevler'
      fullPath: '/gorevler/'
      preLoaderRoute: typeof AppGorevlerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gorevler/$taskId': {
      id: '/_app/gorevler/$taskId'
      path: '/gorevler/$taskId'
      fullPath: '/gorevler/$taskId'
      preLoaderRoute: typeof AppGorevlerTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/isler/': {
      id: '/_app/isler/'
      path: '/isler'
      fullPath: '/isler/'
      preLoaderRoute: typeof AppIslerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/isler/$workId': {
      id: '/_app/isler/$workId'
      path: '/isler/$workId'
      fullPath: '/isler/$workId'
      preLoaderRoute: typeof AppIslerWorkIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mesajlar/': {
      id: '/_app/mesajlar/'
      path: '/mesajlar'
      fullPath: '/mesajlar/'
      preLoaderRoute: typeof AppMesajlarIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mesajlar/$campaignId': {
      id: '/_app/mesajlar/$campaignId'
      path: '/mesajlar/$campaignId'
      fullPath: '/mesajlar/$campaignId'
      preLoaderRoute: typeof AppMesajlarCampaignIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mesajlar/yeni': {
      id: '/_app/mesajlar/yeni'
      path: '/mesajlar/yeni'
      fullPath: '/mesajlar/yeni'
      preLoaderRoute: typeof AppMesajlarYeniRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/odeme/sonuc': {
      id: '/_app/odeme/sonuc'
      path: '/odeme/sonuc'
      fullPath: '/odeme/sonuc'
      preLoaderRoute: typeof AppOdemeSonucRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/talepler/': {
      id: '/_app/talepler/'
      path: '/talepler'
      fullPath: '/talepler/'
      preLoaderRoute: typeof AppTaleplerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/talepler/$requestId': {
      id: '/_app/talepler/$requestId'
      path: '/talepler/$requestId'
      fullPath: '/talepler/$requestId'
      preLoaderRoute: typeof AppTaleplerRequestIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/taleplerim/': {
      id: '/_app/taleplerim/'
      path: '/taleplerim'
      fullPath: '/taleplerim/'
      preLoaderRoute: typeof AppTaleplerimIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/taleplerim/$requestId': {
      id: '/_app/taleplerim/$requestId'
      path: '/taleplerim/$requestId'
      fullPath: '/taleplerim/$requestId'
      preLoaderRoute: typeof AppTaleplerimRequestIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAidatRoute: typeof AppAidatRoute
  AppAidatAyarlariRoute: typeof AppAidatAyarlariRoute
  AppBankaHareketleriRoute: typeof AppBankaHareketleriRoute
  AppBildirimlerRoute: typeof AppBildirimlerRoute
  AppBorclarRoute: typeof AppBorclarRoute
  AppCalisanRaporuRoute: typeof AppCalisanRaporuRoute
  AppDairemRoute: typeof AppDairemRoute
  AppExcelAktarmaRoute: typeof AppExcelAktarmaRoute
  AppFirmalarRoute: typeof AppFirmalarRoute
  AppGelirGiderRoute: typeof AppGelirGiderRoute
  AppGiderlerRoute: typeof AppGiderlerRoute
  AppIslemGecmisiRoute: typeof AppIslemGecmisiRoute
  AppKasaRoute: typeof AppKasaRoute
  AppKasaAyarlariRoute: typeof AppKasaAyarlariRoute
  AppMarkaRoute: typeof AppMarkaRoute
  AppMesajAyarlariRoute: typeof AppMesajAyarlariRoute
  AppPanelRoute: typeof AppPanelRoute
  AppRaporlarRoute: typeof AppRaporlarRoute
  AppSakinlerRoute: typeof AppSakinlerRoute
  AppSifreRoute: typeof AppSifreRoute
  AppSitelerRoute: typeof AppSitelerRoute
  AppTahsilatlarRoute: typeof AppTahsilatlarRoute
  AppTekrarlayanGorevlerRoute: typeof AppTekrarlayanGorevlerRoute
  AppVardiyalarRoute: typeof AppVardiyalarRoute
  AppYetkililerRoute: typeof AppYetkililerRoute
  AppIndexRoute: typeof AppIndexRoute
  AppButceBudgetIdRoute: typeof AppButceBudgetIdRoute
  AppCalisanlarEmployeeIdRoute: typeof AppCalisanlarEmployeeIdRoute
  AppDairelerUnitIdRoute: typeof AppDairelerUnitIdRoute
  AppDuyurularAnnouncementIdRoute: typeof AppDuyurularAnnouncementIdRoute
  AppGenelKurulMeetingIdRoute: typeof AppGenelKurulMeetingIdRoute
  AppGorevlerTaskIdRoute: typeof AppGorevlerTaskIdRoute
  AppIslerWorkIdRoute: typeof AppIslerWorkIdRoute
  AppMesajlarCampaignIdRoute: typeof AppMesajlarCampaignIdRoute
  AppMesajlarYeniRoute: typeof AppMesajlarYeniRoute
  AppOdemeSonucRoute: typeof AppOdemeSonucRoute
  AppTaleplerRequestIdRoute: typeof AppTaleplerRequestIdRoute
  AppTaleplerimRequestIdRoute: typeof AppTaleplerimRequestIdRoute
  AppButceIndexRoute: typeof AppButceIndexRoute
  AppCalisanlarIndexRoute: typeof AppCalisanlarIndexRoute
  AppDairelerIndexRoute: typeof AppDairelerIndexRoute
  AppDuyurularIndexRoute: typeof AppDuyurularIndexRoute
  AppGenelKurulIndexRoute: typeof AppGenelKurulIndexRoute
  AppGorevlerIndexRoute: typeof AppGorevlerIndexRoute
  AppIslerIndexRoute: typeof AppIslerIndexRoute
  AppMesajlarIndexRoute: typeof AppMesajlarIndexRoute
  AppTaleplerIndexRoute: typeof AppTaleplerIndexRoute
  AppTaleplerimIndexRoute: typeof AppTaleplerimIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAidatRoute: AppAidatRoute,
  AppAidatAyarlariRoute: AppAidatAyarlariRoute,
  AppBankaHareketleriRoute: AppBankaHareketleriRoute,
  AppBildirimlerRoute: AppBildirimlerRoute,
  AppBorclarRoute: AppBorclarRoute,
  AppCalisanRaporuRoute: AppCalisanRaporuRoute,
  AppDairemRoute: AppDairemRoute,
  AppExcelAktarmaRoute: AppExcelAktarmaRoute,
  AppFirmalarRoute: AppFirmalarRoute,
  AppGelirGiderRoute: AppGelirGiderRoute,
  AppGiderlerRoute: AppGiderlerRoute,
  AppIslemGecmisiRoute: AppIslemGecmisiRoute,
  AppKasaRoute: AppKasaRoute,
  AppKasaAyarlariRoute: AppKasaAyarlariRoute,
  AppMarkaRoute: AppMarkaRoute,
  AppMesajAyarlariRoute: AppMesajAyarlariRoute,
  AppPanelRoute: AppPanelRoute,
  AppRaporlarRoute: AppRaporlarRoute,
  AppSakinlerRoute: AppSakinlerRoute,
  AppSifreRoute: AppSifreRoute,
  AppSitelerRoute: AppSitelerRoute,
  AppTahsilatlarRoute: AppTahsilatlarRoute,
  AppTekrarlayanGorevlerRoute: AppTekrarlayanGorevlerRoute,
  AppVardiyalarRoute: AppVardiyalarRoute,
  AppYetkililerRoute: AppYetkililerRoute,
  AppIndexRoute: AppIndexRoute,
  AppButceBudgetIdRoute: AppButceBudgetIdRoute,
  AppCalisanlarEmployeeIdRoute: AppCalisanlarEmployeeIdRoute,
  AppDairelerUnitIdRoute: AppDairelerUnitIdRoute,
  AppDuyurularAnnouncementIdRoute: AppDuyurularAnnouncementIdRoute,
  AppGenelKurulMeetingIdRoute: AppGenelKurulMeetingIdRoute,
  AppGorevlerTaskIdRoute: AppGorevlerTaskIdRoute,
  AppIslerWorkIdRoute: AppIslerWorkIdRoute,
  AppMesajlarCampaignIdRoute: AppMesajlarCampaignIdRoute,
  AppMesajlarYeniRoute: AppMesajlarYeniRoute,
  AppOdemeSonucRoute: AppOdemeSonucRoute,
  AppTaleplerRequestIdRoute: AppTaleplerRequestIdRoute,
  AppTaleplerimRequestIdRoute: AppTaleplerimRequestIdRoute,
  AppButceIndexRoute: AppButceIndexRoute,
  AppCalisanlarIndexRoute: AppCalisanlarIndexRoute,
  AppDairelerIndexRoute: AppDairelerIndexRoute,
  AppDuyurularIndexRoute: AppDuyurularIndexRoute,
  AppGenelKurulIndexRoute: AppGenelKurulIndexRoute,
  AppGorevlerIndexRoute: AppGorevlerIndexRoute,
  AppIslerIndexRoute: AppIslerIndexRoute,
  AppMesajlarIndexRoute: AppMesajlarIndexRoute,
  AppTaleplerIndexRoute: AppTaleplerIndexRoute,
  AppTaleplerimIndexRoute: AppTaleplerimIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  GirisRoute: GirisRoute,
  DavetTokenRoute: DavetTokenRoute,
  SifreYenileTokenRoute: SifreYenileTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
